### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by cmvee** [kevincobain2000/ionic-timeline#1]
Hi there. Great work on the timeline. I'd like to include the code in a commercial app I am working on. 

Could you please add a LICENSE file? I'm sure everyone would greatly appreciate it if you would consider a license that is flexible and allows for commercial use and modification. Maybe MIT? Here is [the MIT license file from the ion-slides-tabs project](https://github.com/cmvee/ion-slides-tabs/blob/master/LICENSE), for example.

Thanks much for your consideration!

**Comment by kevincobain2000** [comment]
Go ahead man! consider this comment as MIT, will add it later!

**Comment by kevincobain2000** [comment]
Added LICENSE to master
