### ISSUE TITLE
No scroll?

### ISSUE THREAD

**Issue by steviecs** [kevincobain2000/ionic-timeline#2]
I added some timeline posts, and I can't appear to scroll down to them. I'm looking through the code to see if it was disabled intentionally?

**Comment by kevincobain2000** [comment]
Hi, no it scrolls all good, there are no config changes, as mostly this lib is about the css.
Perhaps try using just the css in your own project and check it out?
https://github.com/kevincobain2000/ionic-timeline/blob/master/www/css/style.css
