### ISSUE TITLE
Ionic v3 version

### ISSUE THREAD

**Issue by Bramzor** [kevincobain2000/ionic-timeline#3]
Would use it if there was an Ionic 3 version of it. Looks great.

**Comment by kevincobain2000** [comment]
Got it. I ll try and make one soon for v3. Perhaps it'd be a new repository

**Comment by Bramzor** [comment]
Great news! I sure keep an eye open on this repo. If you want to put it in the marketplace and put a price on it, I'm fine with that.

**Comment by kevincobain2000** [comment]
Neh, man. It'd be free don't worry.

**Comment by kevincobain2000** [comment]
There you go
https://github.com/kevincobain2000/ionic-timeline-v3
